/**
* Contient deux arrays d'expression
* listExpressionH et listExpressionF
**/
var listExpressionH = ["Le plus beau langage du monde est celui que tes yeux utilisent.",
"Ahh, ton sourire me renverse…",
"Ton sourire pourrait éclairer le fond de l’océan.",
"Rodin n’aurait pas fait mieux que Toi.",
"Je t’admire.",
"Tu m’inspires.",
"Tu es irremplaçable.",
"Avec toi, on ne s’ennuie jamais.",
"Tu as un goût de paradis.",
"Tu apportes de la lumière à ma vie.",
"Je suis totalement désarçonné par ton intelligence.",
"Mon appareil photo n’est pas à la hauteur de ta beauté.",
"Mon chat t’adore.",
"J’ai mis une seconde pour t’aimer, mais je mettrais une éternité à t’oublier.",
"J’aimerais être un iceberg pour fondre dans le soleil de tes yeux.",
"Tu es le sucre de mes Kellogg’s Corn Flakes.",
"Tu es le champagne qui fait pétiller ma vie.",
"Tu es le fruit de la passion dans ma salade d’agrumes.",
"Tu as plus de charme que Brad Pitt et Angelina Jolie réunis.",
"J’ai des papillons dans le ventre dès que je te vois.",
"On devrait donner ton nom à une fleur.",
"On devrait donner ton nom à une glace.",
"Les parfums aspirent à rivaliser avec ton odeur.",
"Tu as gardé ton âme d'enfant.",
"Avec toi, on ne s'ennuie jamais.",
"L'adjectif « radieux » est fait pour toi.",
"J'adorerais avoir des cheveux comme les tiens.",
"Quelle mine, tu reviens de vacances ?",
"Tu me rends dingue !",
"« T’as d’beaux yeux, tu sais ». Quai des brumes",
"« Je vous aime tellement que je crois que je vais mourir. » La Femme d’à côté de Truffaut",
"« On a beau tout rêver, tu dépasses le rêve. » Victor Hugo",
"« Le jour où ton regard a rencontré mon regard pour la première fois, un rayon est allé de ton cœur au mien, comme l’aurore à une ruine. » Victor Hugo",
"« La courbe de tes yeux fait le tour de mon cœur. » Paul Éluard",
"« C’est à partir de toi que j’ai dit oui au monde. » Paul Éluard",
"« Et ma vie pour tes yeux lentement s’empoisonne. » Guillaume Apollinaire",
"« Je n’ai tant de chance que parce que tu m’aimes. » Goethe",
"« Tu me plais tellement que, quand il t’arrive de n’être pas jolie, je te trouve belle. » Sacha Guitry",
"« Quand je lève les yeux vers vous on dirait que le monde tremble. » Antonin Artaud",
"« Tes yeux sont si profonds que j’y perds la mémoire. » Louis Aragon",
"« Tu me tues. Tu me fais du bien. » Marguerite Duras",
"« Si un jour je meurs et qu’on m’ouvre le cœur, on pourra lire en lettres d’or… je t’aime encore. » William Shakespeare",
"Tu es beau à piquer les yeux des filles. (Aïe !)",
"Tu ressembles à un dieu grec",
"J’aimerais être un clavier de piano pour être perpétuellement caressé par tes doigts.",
"Tu es encore mieux qu’une Licorne,un Phoenix et un Elfe réunis.",
"Tu es beau à en réveiller les morts.",
"Waw ! Tu es le meilleur ! ",
"Waw ! T’es doué"];
var listExpressionF =["Le plus beau langage du monde est celui que tes yeux utilisent.",
"Ahh, ton sourire me renverse…",
"Ton sourire pourrait éclairer le fond de l’océan.",
"Rodin n’aurait pas fait mieux que Toi.",
"Je t’admire.",
"Tu m’inspires.",
"Tu es irremplaçable.",
"Avec toi, on ne s’ennuie jamais.",
"Tu as un goût de paradis.",
"Tu apportes de la lumière à ma vie.",
"Je suis totalement désarçonné par ton intelligence.",
"Mon appareil photo n’est pas à la hauteur de ta beauté.",
"Mon chat t’adore.",
"J’ai mis une seconde pour t’aimer, mais je mettrais une éternité à t’oublier.",
"J’aimerais être un iceberg pour fondre dans le soleil de tes yeux.",
"Tu es le sucre de mes Kellogg’s Corn Flakes.",
"Tu es le champagne qui fait pétiller ma vie.",
"Tu es le fruit de la passion dans ma salade d’agrumes.",
"Tu as plus de charme que Brad Pitt et Angelina Jolie réunis.",
"J’ai des papillons dans le ventre dès que je te vois.",
"On devrait donner ton nom à une fleur.",
"On devrait donner ton nom à une glace.",
"Les parfums aspirent à rivaliser avec ton odeur.",
"Tu as gardé ton âme d'enfant.",
"Avec toi, on ne s'ennuie jamais.",
"L'adjectif « radieux » est fait pour toi.",
"J'adorerais avoir des cheveux comme les tiens.",
"Quelle mine, tu reviens de vacances ?",
"Tu me rends dingue !",
"« T’as d’beaux yeux, tu sais ». Quai des brumes",
"« Je vous aime tellement que je crois que je vais mourir. » La Femme d’à côté de Truffaut",
"« On a beau tout rêver, tu dépasses le rêve. » Victor Hugo",
"« Le jour où ton regard a rencontré mon regard pour la première fois, un rayon est allé de ton cœur au mien, comme l’aurore à une ruine. » Victor Hugo",
"« La courbe de tes yeux fait le tour de mon cœur. » Paul Éluard",
"« C’est à partir de toi que j’ai dit oui au monde. » Paul Éluard",
"« Et ma vie pour tes yeux lentement s’empoisonne. » Guillaume Apollinaire",
"« Je n’ai tant de chance que parce que tu m’aimes. » Goethe",
"« Tu me plais tellement que, quand il t’arrive de n’être pas jolie, je te trouve belle. » Sacha Guitry",
"« Quand je lève les yeux vers vous on dirait que le monde tremble. » Antonin Artaud",
"« Tes yeux sont si profonds que j’y perds la mémoire. » Louis Aragon",
"« Tu me tues. Tu me fais du bien. » Marguerite Duras",
"« Si un jour je meurs et qu’on m’ouvre le cœur, on pourra lire en lettres d’or… je t’aime encore. » William Shakespeare",
"Tu es belle à piquer les yeux des filles. (Aïe !)",
"Tu n’as pas besoin de maquillage. Really ?",
"Tu ressembles à une déesse grecque.",
"J’aimerais être un clavier de piano pour être perpétuellement caressée par tes doigts.",
"Tu es encore mieux qu’une Licorne, une Sirène et une Elfe réunis.",
"Tu es belle à en réveiller les morts.",
"Waw ! Tu es la meilleure ! ",
"Waw ! T’es douée"];
